POST localhost:9090/user/register
Content-Type: application/json

{
  "username": "quhao2",
  "password": "password",
  "display_name": "Qu Hao 2",
  "labels": [
    "LA",
    "LB",
    "LC"
  ]
}

###
GET http://localhost:9090/user/quhao1