POST localhost:9090/user/register
Content-Type: application/json

{
  "username": "quhao5",
  "password": "password",
  "display_name": "Qu Hao 5",
  "labels": [
    "LA-quhao5",
    "LB-quhao5",
    "LC-quhao5"
  ]
}

###
POST http://localhost:9090/user/auth
Content-Type: application/json

{
  "username": "quhao2",
  "password": "password"
}

###
POST http://localhost:9090/blog/create
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjU2NDNlZDAyLWIwODEtNDdlNi04MTk5LTdmNTI3ZTIzZjQ5MyJ9.eyJ1c2VybmFtZSI6InF1aGFvMiIsImV4cCI6MTcyMDY5MTk5ODY1MiwibGFiZWxzIjpbXX0.OBw321D32hYo748ULHcSYi4JQ8aTrjbTd0q5roLUeXXCpHasq834UTimmruPtXTDZL28J2aVDkzMfzwCE8uKXQ
Content-Type: application/json

{
  "title": "Title 4-quhao3",
  "summary": "Summary 4-quhao2",
  "labels": [
    "BL1",
    "BL2"
  ]
}

###
GET http://localhost:9090/blog/71f4b37b-e029-49a8-b58e-4408ecb0bf35
Content-Type: application/json

###
POST http://localhost:9090/post/create/4e4f5b2a-fe13-4307-80ea-81f34553170f
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjU2NDNlZDAyLWIwODEtNDdlNi04MTk5LTdmNTI3ZTIzZjQ5MyJ9.eyJ1c2VybmFtZSI6InF1aGFvMiIsImV4cCI6MTcyMDY5MTk5ODY1MiwibGFiZWxzIjpbXX0.OBw321D32hYo748ULHcSYi4JQ8aTrjbTd0q5roLUeXXCpHasq834UTimmruPtXTDZL28J2aVDkzMfzwCE8uKXQ
Content-Type: application/json

{
  "title": "Title 3",
  "content": "Summary 3",
  "labels": [
    "PL1",
    "PL2"
  ]
}

###
GET http://localhost:9090/blog/list/quhao2
Content-Type: application/json

###
GET http://localhost:9090/post/list/4e4f5b2a-fe13-4307-80ea-81f34553170f
Content-Type: application/json

###
GET http://localhost:9090/post/list/labels?labels=LB1&labels=LB2&labels=LB3&labels=LB20&page_index=0&page_size=10
Content-Type: application/json