[package]
name = "ppaass-blog-domain"
version = "0.1.0"
edition = "2021"
[dependencies]
sea-orm = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
anyhow = { workspace = true }
async-trait = { workspace = true }