[database]
database_type = "MySQL"
host = "localhost"
port = 3306
username = "root"
password = "123456"
database_name = "ppaass_blog_db"
max_connections = 32
min_connections = 32
connection_acquire_timeout = 1
[log]
file_name_prefix = "ppaass-blog"
max_log_level = "INFO"
log_folder = "log"